plugins:
  - uses:
      - plugin: https://command-query-user-development.ubiquity.workers.dev
        with:
          allowPublicQuery: true
  - uses:
      - plugin: https://ubiquibot-command-wallet-development.ubiquity.workers.dev
        with:
          registerWalletWithVerification: false
  - uses:
      - plugin: https://ubiquibot-command-wallet-development.ubiquity.workers.dev
        with:
          registerWalletWithVerification: false
  - uses:
      - plugin: https://ubiquibot-command-wallet-development.ubiquity.workers.dev
        with:
          registerWalletWithVerification: false
  - uses:
      - plugin: https://ubiquibot-command-wallet-development.ubiquity.workers.dev
        with:
          registerWalletWithVerification: false
  - uses:
      - plugin: https://ubiquibot-command-wallet-development.ubiquity.workers.dev
        with:
          registerWalletWithVerification: false
  - uses:
      - plugin: https://ubiquibot-command-wallet-development.ubiquity.workers.dev
        with:
          registerWalletWithVerification: false
  - uses:
      - plugin: https://ubiquibot-command-wallet-development.ubiquity.workers.dev
        with:
          registerWalletWithVerification: false
  - uses:
      - plugin: https://ubiquibot-command-wallet-development.ubiquity.workers.dev
        with:
          registerWalletWithVerification: false
  - uses:
      - plugin: https://ubiquibot-command-wallet-development.ubiquity.workers.dev
        with:
          registerWalletWithVerification: false
  - uses:
      - plugin: https://ubiquibot-command-wallet-development.ubiquity.workers.dev
        with:
          registerWalletWithVerification: false
  - uses:
      - plugin: https://ubiquibot-command-wallet-development.ubiquity.workers.dev
        with:
          registerWalletWithVerification: false
  - uses:
      - plugin: https://ubiquibot-command-wallet-development.ubiquity.workers.dev
        with:
          registerWalletWithVerification: false
  - uses:
      - plugin: https://ubiquibot-command-wallet-development.ubiquity.workers.dev
        with:
          registerWalletWithVerification: false
  - uses:
      - plugin: https://ubiquibot-command-wallet-development.ubiquity.workers.dev
        with:
          registerWalletWithVerification: false
  - uses:
      - plugin: https://ubiquibot-command-wallet-development.ubiquity.workers.dev
        with:
          registerWalletWithVerification: false
  - uses:
      - plugin: https://ubiquibot-command-wallet-development.ubiquity.workers.dev
        with:
          registerWalletWithVerification: false
  - uses:
      - plugin: https://ubiquibot-assistive-pricing-development.ubiquity.workers.dev
        with:
          globalConfigUpdate:
            excludeRepos: []
          labels:
            time: []
            priority: []
          basePriceMultiplier: 1
          publicAccessControl:
            setLabel: false
            fundExternalClosedIssue: false
