plugins:
  '*':
    - uses:
      - plugin: ubiquibot/user-activity-watcher
        type: github
        with:
          unassignUserThreshold: 7
          sendRemindersThreshold: 3.5
    - uses:
      - plugin: zug-ubiquity-kernel/conversation-rewards
        type: github
        with:
          evmNetworkId: 100
          evmPrivateEncrypted: "kmpTKq5Wh9r9x5j3U9GqZr3NYnjK2g0HtbzeUBOuLC2y3x8ja_SKBNlB2AZ6LigXHP_HeMitftVUtzmoj8CFfVP9SqjWoL6IPku1hVTWkdTn97g1IxzmjydFxjdcf0wuDW1hvVtoq3Uw5yALABqxcQ"
          incentives:
            enabled: true
            contentEvaluator:
              enabled: true
            userExtractor:
              enabled: true
              redeemTask: true
            dataPurge:
              enabled: true
            formattingEvaluator:
              enabled: true
              scores:
                br: 0
                code: 1
                p: 1
                em: 0
                img: 0
                strong: 0
                blockquote: 0
                h1: 1
                h2: 1
                h3: 1
                h4: 1
                h5: 1
                h6: 1
                a: 1
                li: 1
                td: 1
                hr: 0
              multipliers:
                - type: [ ISSUE, ISSUER, SPECIFICATION ]
                  formattingMultiplier: 1
                  wordValue: 0.1
                - type: [ ISSUE, ISSUER, COMMENTED ]
                  formattingMultiplier: 1
                  wordValue: 0.2
                - type: [ ISSUE, ASSIGNEE, COMMENTED ]
                  formattingMultiplier: 0
                  wordValue: 0
                - type: [ ISSUE, COLLABORATOR, COMMENTED ]
                  formattingMultiplier: 1
                  wordValue: 0.1
                - type: [ ISSUE, CONTRIBUTOR, COMMENTED ]
                  formattingMultiplier: 0.25
                  wordValue: 0.1
                - type: [ REVIEW, ISSUER, TASK ]
                  formattingMultiplier: 0
                  wordValue: 0
                - type: [ REVIEW, ISSUER, COMMENTED ]
                  formattingMultiplier: 2
                  wordValue: 0.2
                - type: [ REVIEW, ASSIGNEE, COMMENTED ]
                  formattingMultiplier: 1
                  wordValue: 0.1
                - type: [ REVIEW, COLLABORATOR, COMMENTED ]
                  formattingMultiplier: 1
                  wordValue: 0.1
                - type: [ REVIEW, CONTRIBUTOR, COMMENTED ]
                  formattingMultiplier: 0.25
                  wordValue: 0.1
            permitGeneration:
              enabled: false
            githubComment:
              enabled: true
              post: true
              debug: false
    - uses:
      - plugin: https://ubiquibot-assistive-pricing.ubq.fi
        type: github
        with:
          labels:
            time:
              - "Time: <1 Hour"
              - "Time: <2 Hours"
              - "Time: <4 Hours"
              - "Time: <1 Day"
              - "Time: <1 Week"
            priority:
              - "Priority: 1 (Normal)"
              - "Priority: 2 (Medium)"
              - "Priority: 3 (High)"
              - "Priority: 4 (Urgent)"
              - "Priority: 5 (Emergency)"
          basePriceMultiplier: 1
          publicAccessControl:
            setLabel: true
            fundExternalClosedIssue: false
    - uses:
      - plugin: https://ubiquibot-command-query-user.ubq.fi
        type: github
        with:
          allowPublicQuery: false